### PR TITLE
Making Websocket Local read-write

### LINKED ISSUE #675: 🤗 [Question]: Must Websocket Locals be read-only?
### Question Description

I notice that the `Locals` are read-only within the Websocket, and I was wonder if there is a reason for that?

I'm looking to persist user context through-out the length of the connection and was hoping to use `Locals`.  

Would something like the below change be feasible? (I can submit a PR if so)

### Code Snippet (optional)

```go
// Locals makes it possible to pass interface{} values under string keys scoped to the request
// and therefore available to all following routes that match the request.
func (conn *Conn) Locals(key string, value ...interface{}) interface{} {
	if len(value) == 0 {
		return conn.locals[key]
	}
	conn.locals[key] = value[0]
	return value[0]
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

### PR DESCRIPTION
**Pull request by supagroova**
Fixes #675

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Thanks for that, can you add the signatures to the readme like the other middlewares?
we plan to improve the readme's and also make them available in our online fiber doc

https://github.com/gofiber/contrib/tree/main/swagger#signatures
https://github.com/gofiber/contrib/tree/main/swagger#signatures
....

https://github.com/gofiber/fiber/blob/453ccadadd09b80155cdde7cc9d1beae9ec91f21/docs/partials/routing/handler.md?plain=1#L8-L26

**Comment by gaby** [comment]
This should wait for #669 so we can test it

**Comment by ReneWerner87** [comment]
@supagroova friendly ping

**Comment by gaby** [comment]
@ReneWerner87 I took care of the merge conflict, do we need another unit-test for these changes? and the README changes.

**Comment by ReneWerner87** [comment]
> @ReneWerner87 I took care of the merge conflict, do we need another unit-test for these changes? and the README changes.

yes would be good

**Comment by gaby** [comment]
I honestly have no idea how to test this, maybe @mstrYoda can help with this unit-test

**Comment by mstrYoda** [comment]
> I honestly have no idea how to test this, maybe @mstrYoda can help with this unit-test

Well I think adding the new if condition as a test scenario to here works well: https://github.com/gofiber/contrib/blob/main/websocket/websocket_test.go#L224

**Comment by ReneWerner87** [comment]
@mstrYoda @gaby is it ready for merge ?

**Comment by mstrYoda** [comment]
> @mstrYoda @gaby is it ready for merge ?

May be we can add unit tests here 🤔  Or we can just merge it as is.

**Comment by gaby** [comment]
I was going to add tests, then i realize i have no idea how to test this 😂

**Comment by mstrYoda** [comment]
> I was going to add tests, then i realize i have no idea how to test this 😂

Well I will add test for this function no worry, we can merge this PR 👍

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
