### PR TITLE
add newrelic middleware, unit tests

### PR DESCRIPTION
**Pull request by mstrYoda**
Resolves: https://github.com/gofiber/contrib/issues/234

Now we can use newrelic as middleware in fiber as follows:

```
app := fiber.New()

app.Get("/", func(ctx *fiber.Ctx) error {
	return ctx.SendStatus(200)
})

cfg := Config{
	License:       "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
	AppName:       "",
	Enabled:       true,
	TransportType: "",
}

app.Use(New(cfg))
```

### CODE REVIEW

**Comment by mstrYoda** [comment]
@ReneWerner87 Hi, can you review the changes when you are available? 🙏

**Review by efectn — CHANGES_REQUESTED** [review]
- [ ] Put middleware into the root README.md
- [ ] Add README.

md for middleware like other contrib middlewares

**Comment by ReneWerner87** [comment]
and don´t forget the github workflows -> otherwise the tests and dependabot .... check will not start for our new middleware

**Comment by mstrYoda** [comment]
> * [ ]  Put middleware into the root README.md
> * [ ]  Add README.
> 
> md for middleware like other contrib middlewares

Thank you for your response. Done 👍 

> and don´t forget the github workflows -> otherwise the tests and dependabot .... check will not start for our new middleware
> 
> * [ ]  adjust github workflow files for the new middleware

Thank you for your response also, done 👍

**Review by ReneWerner87 — APPROVED** [review]

**Review by efectn — APPROVED** [review]

**Pull request merged**
