### PR TITLE
Update otel metric version from v0.37.0 to v0.38.1

### PR DESCRIPTION
**Pull request by danielalvarenga**

### CODE REVIEW

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@danielalvarenga can you check the tests

**Comment by ReneWerner87** [comment]
@danielalvarenga please check the tests

**Comment by danielalvarenga** [comment]
@ReneWerner87 sorry my delay. Tests updated.

**Review by gaby — APPROVED** [review]

**Comment by gaby** [comment]
@ReneWerner87

**Comment by gaby** [comment]
Closes #571 #567

**Comment by gaby** [comment]
@bangbaew 😂 gotta love opentelemetry

**Comment by mstrYoda** [comment]
> Now a new breaking change has been introduced again at otel v0.39 image https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.16.0

Same here...

**Comment by mstrYoda** [comment]
I am working on a fix for new version 1.16 right now

**Pull request merged**
